In [2]:
import cornac 
cornac.datasets.movielens.load_feedback()

[('196', '242', 3.0),
 ('186', '302', 3.0),
 ('22', '377', 1.0),
 ('244', '51', 2.0),
 ('166', '346', 1.0),
 ('298', '474', 4.0),
 ('115', '265', 2.0),
 ('253', '465', 5.0),
 ('305', '451', 3.0),
 ('6', '86', 3.0),
 ('62', '257', 2.0),
 ('286', '1014', 5.0),
 ('200', '222', 5.0),
 ('210', '40', 3.0),
 ('224', '29', 3.0),
 ('303', '785', 3.0),
 ('122', '387', 5.0),
 ('194', '274', 2.0),
 ('291', '1042', 4.0),
 ('234', '1184', 2.0),
 ('119', '392', 4.0),
 ('167', '486', 4.0),
 ('299', '144', 4.0),
 ('291', '118', 2.0),
 ('308', '1', 4.0),
 ('95', '546', 2.0),
 ('38', '95', 5.0),
 ('102', '768', 2.0),
 ('63', '277', 4.0),
 ('160', '234', 5.0),
 ('50', '246', 3.0),
 ('301', '98', 4.0),
 ('225', '193', 4.0),
 ('290', '88', 4.0),
 ('97', '194', 3.0),
 ('157', '274', 4.0),
 ('181', '1081', 1.0),
 ('278', '603', 5.0),
 ('276', '796', 1.0),
 ('7', '32', 4.0),
 ('10', '16', 4.0),
 ('284', '304', 4.0),
 ('201', '979', 2.0),
 ('276', '564', 3.0),
 ('287', '327', 5.0),
 ('246', '201', 5.0),
 ('242'

In [1]:
import cornac
from cornac.eval_methods import RatioSplit
from cornac.models import MF, PMF, BPR
from cornac.metrics import MAE, RMSE, Precision, Recall, NDCG, AUC, MAP

# load the built-in MovieLens 100K and split the data based on ratio
ml_100k = cornac.datasets.movielens.load_feedback(variant="100K")
rs = RatioSplit(data=ml_100k, test_size=0.2, rating_threshold=4.0, seed=123)

# initialize models, here we are comparing: Biased MF, PMF, and BPR
skm = cornac.models.SKMeans(
   k=5,
   max_iter=100,
   tol=1e-10,
   seed=123
)
svd = cornac.models.SVD(
    k=10, max_iter=30, learning_rate=0.01, lambda_reg=0.02, verbose=True
)
mf = MF(k=10, max_iter=25, learning_rate=0.01, lambda_reg=0.02, use_bias=False, seed=123)
pmf = PMF(k=10, max_iter=100, learning_rate=0.001, lambda_reg=0.001, seed=123)
bpr = BPR(k=10, max_iter=200, learning_rate=0.001, lambda_reg=0.01, seed=123)
bivae = cornac.models.BiVAECF(
    k=20,
    encoder_structure=50,
    act_fn="tanh",
    likelihood="pois",
    n_epochs=200,
    batch_size=128,
    learning_rate=0.001,
    seed=123,
    verbose=False
)
models = [skm, svd, mf, pmf, bpr, ]

# define metrics to evaluate the models
metrics = [ Precision(k=10), Recall(k=10), NDCG(k=210), AUC(), MAP()]

# put it together in an experiment, voilà!
#cornac.Experiment(eval_method=rs, models=models, metrics=metrics, user_based=True).run()


c:\cornac\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [14]:
import torch
graph = torch.sparse_coo_tensor(rs.train_set.uir_tuple[0:2], rs.train_set.uir_tuple[2], size = [1000, 20000]).long()
graph

graph.coalesce().indices()

tensor([[   0,    0,    0,  ...,  942,  942,  942],
        [   0,   17,   25,  ...,  815,  873, 1114]])

In [3]:
i = rs.train_set.uij_iter(100)
user, pos, neg = next(i)

In [ ]:
rs.train_set.num_items
torch.sparse.Tensor(rs.train_set.uir_tuple[0:2]).long()

tensor([[  0,   1,   2,  ..., 198,  69, 427],
        [  0,   1,   2,  ...,  30, 429, 644]])

In [4]:
user, pos, neg = next(i)
user, pos, neg

(array([ 73,  45,  20,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
        100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,  53, 111,
        112, 113, 114,  19, 115, 116, 117, 118, 119, 120,  87, 121, 122,
        123, 124,  31,  83, 125,  53,  10, 126, 127, 128, 129, 130, 131,
         62, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145,  96, 146, 147, 148, 149,  66, 150,  51, 151, 152,  83,
         20,  30,  34, 153, 154, 155, 156, 157,  12,  31, 158, 159, 160,
        137, 121,  46, 161, 136, 162, 132,  78, 163]),
 array([ 94,  95,  96,  97,  37,  98,  99, 100, 101, 102, 103, 104, 105,
        106, 107,  33, 108, 109, 110, 111, 105, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122,   6, 123, 124, 125, 126, 127, 128,
        129, 130,  25,  45, 128, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142,  95, 143, 144, 145, 102, 146,  91, 147, 148,
        149,  87, 150, 151, 152,  73, 153, 154,  61, 155, 156, 157, 1

In [ ]:
import torch
import torch.optim as optim
from torch_geometric.nn.models import LightGCN
embed_size = 8
model = LightGCN(rs.train_set.num_items + rs.train_set.num_users, embedding_dim= embed_size, num_layers=1 )
optimizer = optim.Adam(model.parameters(),)


graph = torch.sparse_coo_tensor(train_set.uir_tuple[0], train_set.uir_tuple[1], size = (self.total_users, self.total_items)).long().to(device)


In [9]:
optimizer.zero_grad()
graph = torch.sparse.Tensor(rs.train_set.uir_tuple[0:2]).long()
edge_label_index = torch.cat([
            torch.sparse.Tensor([user,pos]).long(),
            torch.sparse.Tensor([user,neg]).long(),
        ], dim=1)
pos_rank, neg_rank = model.forward(graph, torch.sparse.Tensor([user,pos]).long()).chunk(2)
loss = model.recommendation_loss(
            pos_rank,
            neg_rank,
            node_id=edge_label_index.unique(),
        )

loss.backward()
optimizer.step()
print(loss)


tensor(0.6932, grad_fn=<AddBackward0>)


In [15]:
model.get_embedding(graph)[:rs.train_set.num_items]
model.get_embedding(graph)[rs.train_set.num_items:]

tensor([[ 0.0037, -0.0045,  0.0236,  ..., -0.0101,  0.0016, -0.0110],
        [-0.0160, -0.0082,  0.0205,  ...,  0.0072, -0.0037, -0.0049],
        [-0.0016,  0.0216, -0.0104,  ...,  0.0029,  0.0131,  0.0120],
        ...,
        [-0.0227, -0.0068,  0.0011,  ...,  0.0216, -0.0213, -0.0047],
        [-0.0189, -0.0202, -0.0167,  ...,  0.0137,  0.0082, -0.0160],
        [-0.0177, -0.0104,  0.0105,  ...,  0.0135, -0.0216,  0.0127]],
       grad_fn=<SliceBackward0>)

In [4]:
def fit(self, train_set, val_set=None):
        """Fit the model to observations.

        Parameters
        ----------
        train_set: :obj:`cornac.data.Dataset`, required
            User-Item preference data as well as additional modalities.

        val_set: :obj:`cornac.data.Dataset`, optional, default: None
            User-Item preference data for model selection purposes (e.g., early stopping).

        Returns
        -------
        self : object
        """
        Recommender.fit(self, train_set, val_set)

        if not self.trainable:
            return self

        # model setup
        import torch
        from torch_geometric.nn.models import LightGCN

        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        if self.seed is not None:
            torch.manual_seed(self.seed)
            if torch.cuda.is_available():
                torch.cuda.manual_seed_all(self.seed)

        self.graph_data = torch.sparse_coo_tensor(
            train_set.uir_tuple[0:2],
            train_set.uir_tuple[2],
            # size=[self.total_users, self.total_items],
        ).long()
        self.graph = self.graph_data.coalesce().indices()

        model = LightGCN(
            self.total_users + self.total_items,
            embedding_dim=self.emb_size,
            num_layers=self.num_layers,
        ).to(device)
        model.compile()

        optimizer = torch.optim.Adam(model.parameters(), lr=self.learning_rate)

        # model training
        pbar = trange(
            self.num_epochs,
            desc="Training",
            unit="iter",
            position=0,
            leave=False,
            disable=not self.verbose,
        )
        for _ in pbar:
            model.train()
            accum_loss = total_examples = 0.0
            for batch_user, batch_pos, batch_neg in tqdm(
                train_set.uij_iter(
                    batch_size=self.batch_size,
                    shuffle=True,
                ),
                desc="Epoch",
                total=train_set.num_batches(self.batch_size),
                leave=False,
                position=1,
                disable=not self.verbose,
            ):
                optimizer.zero_grad()
                edge_label_index = torch.cat(
                    [
                        torch.sparse.Tensor([batch_user, batch_pos]).long(),
                        torch.sparse.Tensor([batch_user, batch_neg]).long(),
                    ],
                    dim=1,
                )
                pos_rank, neg_rank = model.forward(self.graph, edge_label_index).chunk(
                    2
                )
                batch_loss = model.recommendation_loss(
                    pos_rank,
                    neg_rank,
                    node_id=batch_user,
                    lambda_reg=self.lambda_reg,
                )
                batch_loss.backward()
                optimizer.step()

                accum_loss += float(batch_loss) * pos_rank.numel()
                total_examples += pos_rank.numel()

            accum_loss /= total_examples  # normalize over all observations
            pbar.set_postfix(loss=accum_loss)

            # store user and item embedding matrices for prediction
            model.eval()

            u_embs = model.get_embedding(self.graph)[: self.total_users]
            i_embs = model.get_embedding(self.graph)[self.total_users :]
            # we will use numpy for faster prediction in the score function, no need torch
            self.U = u_embs.cpu().detach().numpy()
            self.V = i_embs.cpu().detach().numpy()

            if self.early_stopping is not None and self.early_stop(
                train_set, val_set, **self.early_stopping
            ):
                break

In [1]:
import cornac
from cornac.eval_methods import RatioSplit




ml_100k = cornac.datasets.movielens.load_feedback()
rs = RatioSplit(data=ml_100k, test_size=0.2, rating_threshold=4.0, seed=123)
# initialize models, here we are comparing: Biased MF, PMF, and BPR
#mf = MF(k=10, max_iter=25, learning_rate=0.01, lambda_reg=0.02, use_bias=True, seed=123)
#ncf = ncf(k=10, max_iter=100, learning_rate=0.001, lambda_reg=0.001, seed=123)
lightgcn = cornac.models.LightGCN_geom(
    seed=123,
    num_epochs=1000,
    num_layers=3,
    early_stopping={"min_delta": 1e-4, "patience": 50},
    batch_size=1024,
    learning_rate=0.001,
    lambda_reg=1e-4,
    verbose=True
)

rec_20 = cornac.metrics.Recall(k=20)
ndcg_20 = cornac.metrics.NDCG(k=20)

# Put everything together into an experiment and run it
cornac.Experiment(
    eval_method=rs,
    models=[lightgcn],
    metrics=[rec_20, ndcg_20],
    user_based=True,
    save_dir = 'saved_models'
).run()

c:\cornac\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\cornac\venv\lib\site-packages\cornac-2.3.3-py3.10-win-amd64.egg\cornac\models\lightgcn_torch_geom\recom_lightgcn_torch_geom.py:134: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_new.cpp:256.)
  self.graph_data = torch.sparse_coo_tensor(
Training:   0%|          | 0/1000 [00:00<?, ?iter/s]c:\cornac\venv\lib\site-packages\cornac-2.3.3-py3.10-win-amd64.egg\cornac\models\lightgcn_torch_geom\recom_lightgcn_torch_geom.py:193: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected 

LightGCN_geom model is saved to saved_models\LightGCN_geom\2025-08-12_16-48-22-264515.pkl

TEST:
...
              | NDCG@20 | Recall@20 | Train (s) | Test (s)
------------- + ------- + --------- + --------- + --------
LightGCN_geom |  0.0288 |    0.0359 | 7502.2621 |   0.3864



In [1]:
!pip install -U sentence-transformers

     ---------------------------------------- 0.0/483.4 kB ? eta -:--:--
     -- ------------------------------------ 30.7/483.4 kB 1.3 MB/s eta 0:00:01
     ---------------------------- --------- 368.6/483.4 kB 5.7 MB/s eta 0:00:01
     -------------------------------------- 483.4/483.4 kB 5.0 MB/s eta 0:00:00
     ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
     -- ------------------------------------- 0.7/8.9 MB 13.7 MB/s eta 0:00:01
     ----- ---------------------------------- 1.2/8.9 MB 12.5 MB/s eta 0:00:01
     --------- ------------------------------ 2.1/8.9 MB 14.7 MB/s eta 0:00:01
     ------------ --------------------------- 2.9/8.9 MB 15.3 MB/s eta 0:00:01
     ---------------- ----------------------- 3.7/8.9 MB 15.9 MB/s eta 0:00:01
     -------------------- ------------------- 4.6/8.9 MB 17.2 MB/s eta 0:00:01
     ------------------------ --------------- 5.4/8.9 MB 17.3 MB/s eta 0:00:01
     ------------------------ --------------- 5.5/8.9 MB 15.9 M


[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Data(edge_index=[2, 100836], x=[10352, 404], edge_label=[100836], time=[100836], node_type=[10352], edge_type=[100836])

In [45]:
import pandas as pd

import os.path as osp

import torch
from tqdm import tqdm

from torch_geometric.datasets import MovieLens, AmazonBook
from torch_geometric.nn import LightGCN
from torch_geometric.utils import degree

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

path = osp.join(osp.dirname(osp.realpath("./data/")), '..', 'data', 'AmazonBook')
dataset = AmazonBook(path)
data = dataset[0]
num_users, num_books = data['user'].num_nodes, data['book'].num_nodes
data = data.to_homogeneous().to(device)

# Use all message passing edges as training labels:
batch_size = 8192
mask = data.edge_index[0] < data.edge_index[1]
train_edge_label_index = data.edge_index[:, mask]
train_loader = torch.utils.data.DataLoader(
    range(train_edge_label_index.size(1)),
    shuffle=True,
    batch_size=batch_size,
)

model = LightGCN(
    num_nodes=data.num_nodes,
    embedding_dim=64,
    num_layers=2,
).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)



In [40]:
data

Data(edge_index=[2, 100836], x=[10352, 404], edge_label=[100836], time=[100836], node_type=[10352], edge_type=[100836])

In [47]:

def train():
    total_loss = total_examples = 0

    for index in tqdm(train_loader):
        # Sample positive and negative labels.
        pos_edge_label_index = train_edge_label_index[:, index]
        neg_edge_label_index = torch.stack([
            pos_edge_label_index[0],
            torch.randint(num_users, num_users + num_books,
                          (index.numel(), ), device=device)
        ], dim=0)
        edge_label_index = torch.cat([
            pos_edge_label_index,
            neg_edge_label_index,
        ], dim=1)

        optimizer.zero_grad()
        pos_rank, neg_rank = model(data.edge_index, edge_label_index).chunk(2)

        loss = model.recommendation_loss(
            pos_rank,
            neg_rank,
            node_id=edge_label_index.unique(),
        )
        loss.backward()
        optimizer.step()

        total_loss += float(loss) * pos_rank.numel()
        total_examples += pos_rank.numel()

    return total_loss / total_examples


@torch.no_grad()
def test(k: int):
    emb = model.get_embedding(data.edge_index)
    user_emb, book_emb = emb[:num_users], emb[num_users:]

    precision = recall = total_examples = 0
    for start in range(0, num_users, batch_size):
        end = start + batch_size
        logits = user_emb[start:end] @ book_emb.t()

        # Exclude training edges:
        mask = ((train_edge_label_index[0] >= start) &
                (train_edge_label_index[0] < end))
        logits[train_edge_label_index[0, mask] - start,
               train_edge_label_index[1, mask] - num_users] = float('-inf')

        # Computing precision and recall:
        ground_truth = torch.zeros_like(logits, dtype=torch.bool)
        mask = ((data.edge_label_index[0] >= start) &
                (data.edge_label_index[0] < end))
        ground_truth[data.edge_label_index[0, mask] - start,
                     data.edge_label_index[1, mask] - num_users] = True
        node_count = degree(data.edge_label_index[0, mask] - start,
                            num_nodes=logits.size(0))

        topk_index = logits.topk(k, dim=-1).indices
        isin_mat = ground_truth.gather(1, topk_index)

        precision += float((isin_mat.sum(dim=-1) / k).sum())
        recall += float((isin_mat.sum(dim=-1) / node_count.clamp(1e-6)).sum())
        total_examples += int((node_count > 0).sum())

    return precision / total_examples, recall / total_examples


for epoch in range(1, 101):
    loss = train()

    precision, recall = test(k=20)
    print(f'Epoch: {epoch:03d}, Loss: {loss:.4f}, Precision@20: '
            f'{precision:.4f}, Recall@20: {recall:.4f}')

  0%|          | 0/291 [00:00<?, ?it/s]

  1%|▏         | 4/291 [02:15<2:41:56, 33.85s/it]


RuntimeError: bad allocation